# LaTeX {#latex-section}

Similar to GitHub flavored markdown used for posts on GitHub, LaTeX is a markup language that is used to write documents in a very organized manner by typing short commands. LaTeX commands are more customizable and are longer than GitHub flavored markdown commands. In ECN 310, we use the LaTeX markup language to write the final paper. The platform in which we write LaTeX documents is a free website called Overleaf. LaTeX is the language and gives commands on what the document should look like,  and Overleaf is the system used to understand the language and produce the document.

Here’s an example of how Github-flavored markdown and LaTeX compare: 

- In GitHub, text is italicized by placing underscores around it, **\_like so\_**
- But in LaTeX, text is italicized by using a command **\\textit\{like so\}**

There are also commands that are used to structure the document. If an author wanted the document to have a section header called “Introduction”, the author would use the following command: **\\section\{Introduction\}**

You can read through this [explainer](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes) from Overleaf on how LaTeX is used to structure and format documents to make them polished and professional. If you want to test out using LaTeX, you can use this [LaTeX sandbox](https://latex-sandbox.vercel.app/) to experiment with creating simple documents.

You can also make an account on Overleaf and view templates to see how LaTeX used in Overleaf creates well-formatted documents. To join Overleaf, click on this [link](https://www.overleaf.com/register) and sign up! You can use a personal or school email.

Once you are registered for Overleaf, you can see how LaTeX commands form a document by looking at the templates that Overleaf provides. You can find many [here](https://www.overleaf.com/latex/templates). These may look long and complex, but these files become manageable once you start working with them. There are also plenty of resources on the web that can help you figure out what commands mean and where to use them. If you have a question, we suggest two options for getting it answered:

1. Look in the Overleaf documentation, found here: https://www.overleaf.com/learn.
2. Put your question in either Google or your favorite AI companion (both [ChatGPT](https://chat.openai.com/) and [claude.ai](http://claude.ai) work well for these kinds of questions). This is good practice–you’ll often use these tools in the process of learning to code for ECN 310.

When you begin making your own LaTeX file in Overleaf for your course project, you will start with a template provided by Professor Buzard. You can view it with this [link](https://github.com/ecn310/SummerResource/blob/main/placeholder_project_template.tex). As you can see in the ECN 310 template, the document does not start out with too many commands. When building and writing your project, you will use more LaTeX commands to add features to your paper, such as tables and figures. If you want to see the LaTeX file from a past ECN 310 team, you can look at the [zip-center-crime's](https://github.com/ecn310/course-project-zipcentercrime/blob/main/Final%20Report/course_project_zipcentercrime.tex).